import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { usePingQuery } from "../generated/graphql";

const Home: NextPage = () => {
  const { data } = usePingQuery();
  console.log(data);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/yta.jpg" />
      </Head>

      <h1 className="text-3xl font-bold underline">Hello world!</h1>
    </div>
  );
};

export default Home;
