import Head from "next/head";
import { usePingQuery } from "../../generated/graphql";
import Hero from "./Hero";

const Home: React.FunctionComponent = () => {
  const { data } = usePingQuery();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/yta.jpg" />
      </Head>
      <Hero />
    </>
  );
};

export default Home;
